name: Manual Release Build

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34 # Laisse Gradle installer ce qu'il manque; ajuste si besoin
          cmake: "default"
          ndk: "default"

      - name: Decode keystore and create local.properties
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > ${{ github.workspace }}/release-key.jks
          touch local.properties
          echo "STORE_FILE_PATH=${{ github.workspace }}/release-key.jks" >> local.properties
          echo "STORE_PASSWORD=${ANDROID_KEYSTORE_PASSWORD}" >> local.properties
          echo "STORE_KEY=${ANDROID_KEY_ALIAS}" >> local.properties

      - name: Show Gradle version
        run: ./gradlew --version

      - name: Ktlint & Unit tests (release)
        run: ./gradlew ktlintCheck :app:testReleaseUnitTest --stacktrace

      - name: Build Release APK & AAB
        # Ton build.gradle appelle ktlint avant preBuild donc ok
        run: ./gradlew :app:assembleRelease :app:bundleRelease --stacktrace

      - name: Generate Coverage
        run: ./gradlew koverXmlReport

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: contacto-apk-release
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: contacto-aab-release
          path: app/build/outputs/bundle/release/*.aab
          if-no-files-found: error

      - name: Upload Reports (lint/ktlint/kover)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/**
            **/build/kover/**
